const PDFDocument = require("pdfkit");

const buildReportPDF = (res, { title, period, sections }) => {
  const doc = new PDFDocument({ margin: 50, size: "A4" });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    'attachment; filename="' + title.replace(/\s+/g, "_") + '.pdf"',
  );
  doc.pipe(res);

  // Header
  doc
    .fontSize(20)
    .fillColor("#c62828")
    .text("UMARU MUSA YAR'ADUA UNIVERSITY, KATSINA", { align: "center" });
  doc.moveDown(0.3);
  doc
    .fontSize(11)
    .fillColor("#444")
    .text("Smart Task Management System", { align: "center" });
  doc.moveDown(0.3);
  doc.fontSize(15).fillColor("#111").text(title, { align: "center" });
  doc.moveDown(0.2);
  doc
    .fontSize(10)
    .fillColor("#666")
    .text("Period: " + period, { align: "center" });
  doc.text("Generated: " + new Date().toLocaleString(), { align: "center" });
  doc.moveDown(1);

  doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor("#c62828").stroke();
  doc.moveDown(1);

  sections.forEach((section) => {
    doc.fontSize(13).fillColor("#111").text(section.heading);
    doc.moveDown(0.4);

    if (section.type === "kv") {
      section.data.forEach((row) => {
        doc
          .fontSize(10)
          .fillColor("#333")
          .text(row.label + ": " + row.value);
        doc.moveDown(0.2);
      });
    } else if (section.type === "table") {
      const colWidths = section.columns.map(() => 475 / section.columns.length);
      let y = doc.y;
      doc.fontSize(10).fillColor("#c62828");
      section.columns.forEach((c, i) => {
        doc.text(c, 50 + colWidths.slice(0, i).reduce((a, b) => a + b, 0), y, {
          width: colWidths[i],
        });
      });
      y += 18;
      doc
        .moveTo(50, y - 4)
        .lineTo(545, y - 4)
        .strokeColor("#ccc")
        .stroke();
      doc.fillColor("#333").fontSize(9);
      section.rows.forEach((row) => {
        let maxY = y;
        row.forEach((cell, i) => {
          doc.text(
            String(cell),
            50 + colWidths.slice(0, i).reduce((a, b) => a + b, 0),
            y,
            { width: colWidths[i] },
          );
          maxY = Math.max(maxY, doc.y);
        });
        y = maxY + 6;
        if (y > 760) {
          doc.addPage();
          y = 60;
        }
      });
    }
    doc.moveDown(1.2);
  });

  doc.moveDown(1);
  doc
    .fontSize(9)
    .fillColor("#999")
    .text(
      "This is an official report generated by Umaru Musa Yar'adua University, Katsina — Smart Task Management System.",
      { align: "center" },
    );

  doc.end();
};

module.exports = { buildReportPDF };
